alias dcxt="docker context use"
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dc="docker context ls"
alias dl="docker logs"
alias dv="docker volume ls"
alias di="docker image ls"
alias dnuke='docker rm -f $(docker ps -q)'
alias d='docker ps --format "table {{.Names}}\t{{.Status}}"'
alias dd='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Names}}\t{{.CreatedAt}}\t{{.Status}}\t{{.Ports}}"'
alias da="docker ps -a"
