export PATH=$PATH:/opt/homebrew/bin
# vicmd
bindkey -v

export EDITOR=nvim
eval $(thefuck --alias)
eval "$(zoxide init zsh)"
# Kai's Aliases
source "$HOME/.config/zsh/git_alias.zsh"
alias zo="zoxide"
alias ll="eza -laBhHF"
alias lg="eza -laBhHF --git-repos --git --no-permissions"
alias config="z $HOME/.config; v .; z -"
alias cb="pbcopy"
# alias split="split_tab"
alias v="nvim"
alias rm="trash"
alias zela="zellij a"
alias kan="sudo ~/Applications/kanata_macos_arm64 --cfg ~/.config/kanata/kanata_mod.kbd > /dev/null"
alias y="yazi"
alias cd="z"
alias terra-a="terraform apply -auto-approve"
alias fdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
alias s="tmux a -t spot || tmux new-session -s spot '(sleep 5; sketchybar --set ncspot drawing=on) &; ncspot'"
alias sp="tmux send-keys -t spot 'P'"
alias skbr="sketchybar --reload"

expand-all-aliases() {
  local last_word="${LBUFFER##* }"
  local before_last="${LBUFFER%$last_word}"

  # Check if it's an alias
  local expanded
  expanded="$(alias "$last_word" 2>/dev/null | sed -E "s/^$last_word='(.*)'$/\1/")"

  if [[ -n "$expanded" ]]; then
    LBUFFER="${before_last}${expanded}"
  fi
}

zle -N expand-all-aliases
bindkey '^@' expand-all-aliases  # Ctrl-Space

# autoload -U +X bashcompinit && bashcompinit
# complete -o nospace -C /opt/homebrew/bin/terraform terraform

# workaround for a bug that happens when startship is initialised multiple times
# see: https://github.com/starship/starship/issues/3418#issuecomment-1711630970
type starship_zle-keymap-select >/dev/null || \
  {
    eval "$(starship init zsh)"
  }
